[profile.default]
ignored_error_codes = ["2018"]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

# Remappings for imports
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/"
]

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Test settings
verbosity = 2