[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/src/v0.8/"
]

optimizer = true
optimizer_runs = 200
verbosity = 2
